//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Empleados
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_Pagos
    {
        public int Cédula { get; set; }
        public string Nombre { get; set; }
        public string Primer_Apellido { get; set; }
        public string Segundo_Apellido { get; set; }
        public string Puesto_de_Trabajo { get; set; }
        public decimal Monto { get; set; }
        public System.DateTime Fecha { get; set; }
    }
}
